services:
  postgres:
    image: postgres:15-alpine
    container_name: studenthub_postgres
    environment:
      POSTGRES_DB: studenthubdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - studenthub_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: studenthub_backend
    environment:
      ConnectionStrings__PgSql: "Host=postgres;Port=5432;Database=studenthubdb;Username=postgres;Password=password123"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - studenthub_network
    volumes:
      - uploads:/app/uploads
      - ./Backend/StudentHub.Api/logs:/app/logs

  frontend:
    build:
      context: ./frontend
      dockerfile: .dockerfile
    container_name: studenthub_frontend
    ports:
      - "3000:3000"
    networks:
      - studenthub_network

volumes:
  postgres_data:
  uploads:

networks:
  studenthub_network:
    driver: bridge
